version: "3"

services:
  serviceName:
    image: droidwiki/discord-player-count
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    environment:
      PLAYER_COUNT_PROVIDER: cftools_cloud
      CFTOOLS_HOSTNAME: 193.25.252.49
      CFTOOLS_PORT: 2402
      #DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_PUBLISHER_MESSAGE_FORMAT: '$${playerCount}/$${maxPlayers} $${queuedPlayersMessage}'
      DISCORD_PUBLISHER_MESSAGE_QUEUED_FORMAT: '(+$${queuedPlayers})'
      # You need more configuration here, look at the Configuration section
